In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#df = pd.read_csv(r'C:\Users\Tianx\Desktop\Master\ss22_ds\depression.csv')
df = pd.read_csv(r'/content/data_clean_hobbies-hangout.csv') #Tian
#dfh =pd.read_csv(r'/content/data_clean_hobbies-hangout.csv')
#df = pd.read_csv(r'/content/ds_data2022/depression.csv') #Emma
df.head()

Unnamed: 0    mood  age  gender      subject  semester  sibilings  \
0           0  Tensed   24  Female  Engineering         9          3   
1           1  Tensed   23    Male  Engineering        11          3   
2           2     Sad   19  Female     Pharmacy         3          0   
3           3    Lost   23  Female  Engineering        13          1   
4           4    Lost   22    Male  Engineering        11          1   

        living employment personality  ...    exercise  meditation  \
0  With family  Part time   Extrovert  ...  Not at all  Not at all   
1  With family       None    Ambivert  ...   Regularly   Sometimes   
2  With family       None    Ambivert  ...   Sometimes  Not at all   
3  With family       None   Introvert  ...  Not at all  Not at all   
4  With family       None    Ambivert  ...   Sometimes  Not at all   

  video_games study_hours phone_hours medication  movies_per_week  \
0  Not at all           2      6 to 8         No                0   
1   Sometimes           4      0 to 2         No                5   
2  Not at all           3      6 to 8         No                0   
3  Very Often           1      0 to 2         No                5   
4  Very Often           2      6 to 8         No                1   

   music hours  depression  category  
0            0          18  Moderate  
1            0           1      None  
2            0          21    Severe  
3            0          23    Severe  
4            4          19  Moderate  

[5 rows x 35 columns]

In [ ]:
df.head()

Unnamed: 0    mood  age  gender      subject  semester  sibilings  \
0           0  Tensed   24  Female  Engineering         9          3   
1           1  Tensed   23    Male  Engineering        11          3   
2           2     Sad   19  Female     Pharmacy         3          0   
3           3    Lost   23  Female  Engineering        13          1   
4           4    Lost   22    Male  Engineering        11          1   

        living employment personality  ...    exercise  meditation  \
0  With family  Part time   Extrovert  ...  Not at all  Not at all   
1  With family       None    Ambivert  ...   Regularly   Sometimes   
2  With family       None    Ambivert  ...   Sometimes  Not at all   
3  With family       None   Introvert  ...  Not at all  Not at all   
4  With family       None    Ambivert  ...   Sometimes  Not at all   

  video_games study_hours phone_hours medication  movies_per_week  \
0  Not at all           2      6 to 8         No                0   
1   Sometimes           4      0 to 2         No                5   
2  Not at all           3      6 to 8         No                0   
3  Very Often           1      0 to 2         No                5   
4  Very Often           2      6 to 8         No                1   

   music hours  depression  category  
0            0          18  Moderate  
1            0           1      None  
2            0          21    Severe  
3            0          23    Severe  
4            4          19  Moderate  

[5 rows x 35 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 754 entries, 0 to 753
Data columns (total 35 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Unnamed: 0       754 non-null    int64 
 1   mood             754 non-null    object
 2   age              754 non-null    int64 
 3   gender           754 non-null    object
 4   subject          754 non-null    object
 5   semester         754 non-null    int64 
 6   sibilings        754 non-null    int64 
 7   living           754 non-null    object
 8   employment       754 non-null    object
 9   personality      754 non-null    object
 10  relationship     754 non-null    object
 11  wakeup           754 non-null    object
 12  breakfast        754 non-null    object
 13  launch           754 non-null    object
 14  dinner           754 non-null    object
 15  sleep            754 non-null    object
 16  hobbies          754 non-null    int64 
 17  smoker           754 non-null    in

In [ ]:
(df.isnull()).sum()

Unnamed: 0         0
mood               0
age                0
gender             0
subject            0
semester           0
sibilings          0
living             0
employment         0
personality        0
relationship       0
wakeup             0
breakfast          0
launch             0
dinner             0
sleep              0
hobbies            0
smoker             0
alcoholic          0
drug_addicted      0
friends            0
hangout            0
social_events      0
pray               0
sports             0
exercise           0
meditation         0
video_games        0
study_hours        0
phone_hours        0
medication         2
movies_per_week    0
music hours        0
depression         0
category           0
dtype: int64

In [ ]:
df.loc[df.isna().any(1)] 

Unnamed: 0    mood  age gender      subject  semester  sibilings  \
8            8  Tensed   24   Male  Engineering        13          2   
78          78  Tensed   22   Male     Business         8          3   

         living employment personality  ...    exercise  meditation  \
8   With family       None   Introvert  ...  Not at all  Not at all   
78  With family       None    Ambivert  ...  Not at all  Not at all   

   video_games study_hours  phone_hours medication  movies_per_week  \
8   Very Often           1       3 to 5        NaN            1-Jan   
78       Often           2  more than 8        NaN                2   

    music hours  depression  category  
8             0           9  Moderate  
78            0          17  Moderate  

[2 rows x 35 columns]

In [ ]:
df.duplicated(keep=False)

0      False
1      False
2      False
3      False
4      False
       ...  
749    False
750    False
751    False
752    False
753    False
Length: 754, dtype: bool

In [ ]:
###emma
df["mood"].value_counts() # no problem

Happy     283
Tensed    188
Lost      155
Sad       108
Angry      20
Name: mood, dtype: int64

In [ ]:
df["age"].value_counts() #no problem

22    144
23    143
21    133
24    116
25     80
20     73
19     21
26     17
18     10
27      6
28      3
33      2
30      2
29      2
31      1
17      1
Name: age, dtype: int64

In [ ]:
df["gender"].value_counts() #no problem

Male      474
Female    278
Others      2
Name: gender, dtype: int64

In [ ]:
#subject
df["subject"].value_counts()  

Engineering                  383
Business                     207
Pharmacy                      28
MBBS                          16
Law                           15
                            ... 
IR                             1
Environmental Management       1
Environmental management       1
Botany                         1
Hsc                            1
Name: subject, Length: 69, dtype: int64

In [ ]:
#lower
df["subject"] = df["subject"].str.lower()
#remove space
df["subject"] = df['subject'].str.strip()

df["subject"].value_counts() 

engineering                                  383
business                                     207
pharmacy                                      28
mbbs                                          16
law                                           15
economics                                     12
english literature                             8
microbiology                                   7
architecture                                   7
biochemistry and biotechnology                 7
english linguistics                            6
biochemistry                                   5
college                                        4
botany                                         3
environmental science                          3
environmental management                       2
mathematics                                    2
physics                                        2
international relations                        2
hsc                                            2
bba                 

In [ ]:
#re-classificate the subject 
for item in df['subject']:
    if(item == "business" or item == "economics" or item == "hsc" or item == "bba" or item == "marketing" or item =="bba in finance" or item == "hsc 20"):
        df['subject'].replace(item, 'business', inplace = True) 
        continue
    elif(item == 'engineering' or item == "esm"):
        df['subject'].replace(item, 'engineering', inplace = True) 
        continue       
    elif(item == 'bio and medical' or item == "mbbs" or item == "bpt" or item == "microbiology" or item == "biochemistry" or item == "biochemistry and biotechnology" or item == "botany" or item == "genetic engineering and biotechnology" or item == "life sciences" or item == "biotechnology and biochemistry" or item == "biochemistry and molecular biology" or item == "pharmacy"):
        df['subject'].replace(item, 'bio and medical', inplace = True) 
        continue        
    elif(item == 'social' or item == "law" or item == "international relations" or item == "ir" or item == "social work" or item == "social sciences and humanities" or item == "political science" or item =="college/humanities" or item == "college" or item == "criminology" or item == "child development and social relationship"):
        df['subject'].replace(item, 'social', inplace = True) 
        continue       
    elif(item == 'literature' or item == "english literature" or item == "english linguistics" or item == "tesol" or item == "linguistics"):
        df['subject'].replace(item, 'literature', inplace = True)
        continue   
    elif(item == "environment" or item == "environmental science" or item == "environmental management" or item == "geography & environment" or item == "environment management" or item == "environmental science and management"):
        df['subject'].replace(item, 'environment', inplace = True)
        continue      
    elif(item == 'architecture' or item == "interior architecture"):
        df['subject'].replace(item, 'architecture', inplace = True)
        continue
    elif(item == 'math. and cs' or item == 'cse' or item == 'it' or item == 'mathematics'):
        df['subject'].replace(item, 'math. and cs', inplace = True)
        continue
    else:
        df['subject'].replace(item, 'others', inplace = True)



df["subject"].value_counts() 

engineering        384
business           226
bio and medical     71
social              28
literature          16
others               9
architecture         8
environment          8
math. and cs         4
Name: subject, dtype: int64

In [ ]:
#semester
df["semester"].value_counts()

# collage year bigger than age +6 , delete this column
for i in range(len(df)):
    se = df['semester'].get(i)
    age =df["age"].get(i)
    if age - se < 6:
        df.drop([i])

#should delete 1 rows
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 754 entries, 0 to 753
Data columns (total 35 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Unnamed: 0       754 non-null    int64 
 1   mood             754 non-null    object
 2   age              754 non-null    int64 
 3   gender           754 non-null    object
 4   subject          754 non-null    object
 5   semester         754 non-null    int64 
 6   sibilings        754 non-null    int64 
 7   living           754 non-null    object
 8   employment       754 non-null    object
 9   personality      754 non-null    object
 10  relationship     754 non-null    object
 11  wakeup           754 non-null    object
 12  breakfast        754 non-null    object
 13  launch           754 non-null    object
 14  dinner           754 non-null    object
 15  sleep            754 non-null    object
 16  hobbies          754 non-null    int64 
 17  smoker           754 non-null    in

In [ ]:
# semster < 15 keep，>16 as 16+
for item in df['semester']: 
    if item >= 15:  
        df['semester'].replace(item, '15+', inplace = True)
    
df['semester'].value_counts()

5      108
11      94
12      85
8       68
10      56
4       47
1       47
7       40
2       39
9       37
6       35
13      30
3       27
15+     21
14      20
Name: semester, dtype: int64

In [ ]:
#siblings
df["sibilings"].value_counts()

1     315
2     222
3     119
0      64
4      18
5       5
6       5
8       2
7       1
13      1
10      1
20      1
Name: sibilings, dtype: int64

In [ ]:
df["living"].value_counts()

With family       707
Without family     47
Name: living, dtype: int64

In [ ]:
# more than 7 siblings is 7+
for item in df['sibilings']: 
    if item >= 7:  
        df['sibilings'].replace(item, '7+', inplace = True)
    
df["sibilings"].value_counts()

1     315
2     222
3     119
0      64
4      18
7+      6
5       5
6       5
Name: sibilings, dtype: int64

In [ ]:
df["employment"] = df["employment"].str.strip()
df["employment"] = df["employment"].str.lower()
employment_mapper = {"none":0, "part time":1, "full time":2}
df["employment"] = df["employment"].replace(employment_mapper)
df['employment'].unique()

array([1, 0, 2])

In [ ]:
df["living"] = df["living"].str.strip()
df["living"] = df["living"].str.lower()
living_mapper = {"with family":0, "without family":1}
df["living"] = df["living"].replace(living_mapper)
df['living'].unique()

array([0, 1])

In [ ]:
df["personality"] = df["personality"].str.strip()
df["personality"] = df["personality"].str.lower()
personality_mapper = {"extrovert":0, "ambivert":1, "introvert":2}
df["personality"] = df["personality"].replace(personality_mapper)
df['personality'].unique()

array([0, 1, 2])

In [ ]:
df["relationship"] = df["relationship"].str.strip()
df["relationship"] = df["relationship"].str.lower()
relationship_mapper = {"in a relationship":0, "single":1, "engaged":2, "divorced":3, "married":4}
df["relationship"] = df["relationship"].replace(relationship_mapper)
df['relationship'].unique()

array([0, 1, 2, 3, 4])

In [ ]:
df['wakeup'].unique()

array(['11:20:00 AM', '12:00:00 PM', '8:30:00 AM', '2:00:00 PM',
       '11:00:00 AM', '10:00:00 AM', '9:30:00 AM', '9:00:00 AM',
       '9:40:00 AM', '8:00:00 AM', '6:00:00 AM', '5:00:00 AM',
       '7:00:00 AM', '4:00:00 PM', '9:20:00 AM', '12:30:00 PM',
       '7:50:00 AM', '1:00:00 PM', '3:00:00 PM', '12:15:00 PM',
       '12:10:00 AM', '6:10:00 AM', '7:30:00 AM', '11:12:00 AM',
       '5:30:00 AM', '11:30:00 AM', '10:30:00 AM', '6:30:00 AM',
       '12:12:00 PM', '6:00:00 PM', '1:30:00 PM', '11:15:00 AM',
       '4:00:00 AM', '3:00:00 AM', '9:15:00 AM', '1:30:00 AM',
       '12:05:00 AM', '9:21:00 AM', '4:30:00 AM', '1:00:00 AM',
       '11:38:00 AM', '9:00:00 PM', '11:50:00 AM', '8:45:00 AM',
       '4:50:00 AM', '9:45:00 AM', '12:00:00 AM', '8:50:00 AM',
       '5:20:00 AM', '8:20:00 AM', '12:08:00 AM', '6:45:00 AM',
       '5:15:00 AM', '4:35:00 AM', '7:45:00 AM', '10:20:00 AM',
       '12:01:00 PM', '7:38:00 AM', '8:45:00 PM', '4:20:00 AM',
       '12:09:00 AM', '9:09:00 AM', 

In [ ]:
df['breakfast'].unique()

array(['1:10:00 AM', '12:15:00 PM', '10:00:00 AM', '3:00:00 PM',
       '11:30:00 AM', '4:00:00 PM', '11:00:00 AM', '1:00:00 PM',
       '10:30:00 AM', '11:10:00 AM', '2:00:00 PM', '12:00:00 PM',
       '9:15:00 AM', '8:30:00 AM', '9:00:00 AM', '11:11:00 AM',
       '7:00:00 AM', '11:20:00 AM', '12:00:00 AM', '8:03:00 AM',
       '9:30:00 AM', '1:30:00 PM', '12:30:00 PM', '12:11:00 AM',
       '11:15:00 AM', '2:50:00 PM', '1:01:00 PM', '6:00:00 AM',
       '10:15:00 AM', '8:00:00 AM', '2:30:00 PM', '1:12:00 PM',
       '9:20:00 AM', '10:00:00 PM', '6:30:00 AM', '9:50:00 AM',
       '9:45:00 AM', '10:30:00 PM', '3:07:00 PM', '8:20:00 AM',
       '1:00:00 AM', '10:20:00 AM', '11:25:00 AM', '7:30:00 AM',
       '10:50:00 AM', '9:40:00 AM', '10:45:00 AM', '8:50:00 AM',
       '7:45:00 AM', '11:45:00 AM', '12:20:00 PM', '2:00:00 AM',
       '9:10:00 AM', '1:03:00 PM', '11:00:00 PM', '2:15:00 PM',
       '6:45:00 AM', '11:11:00 PM', '2:45:00 PM', '1:07:00 PM',
       '10:52:00 AM', '8:10:00 

In [ ]:
df['launch'].unique()

array(['4:20:00 PM', '4:30:00 PM', '3:00:00 PM', '7:00:00 PM',
       '3:00:00 AM', '2:00:00 PM', '2:30:00 PM', '4:00:00 PM',
       '2:45:00 PM', '8:00:00 PM', '2:40:00 PM', '2:00:00 AM',
       '12:00:00 AM', '3:30:00 PM', '1:30:00 PM', '2:10:00 PM',
       '6:00:00 PM', '2:30:00 AM', '5:00:00 PM', '2:50:00 PM',
       '6:30:00 PM', '5:45:00 PM', '12:04:00 PM', '1:01:00 PM',
       '1:30:00 AM', '4:00:00 AM', '1:45:00 PM', '1:00:00 PM',
       '4:45:00 PM', '3:30:00 AM', '1:00:00 AM', '3:07:00 PM',
       '5:30:00 PM', '12:00:00 PM', '1:45:00 AM', '2:20:00 PM',
       '3:45:00 PM', '2:15:00 AM', '12:02:00 PM', '4:30:00 AM',
       '3:15:00 AM', '5:00:00 AM', '1:38:00 PM', '5:25:00 PM',
       '4:15:00 PM', '5:03:00 PM', '12:05:00 PM', '2:15:00 PM',
       '4:04:00 PM', '3:15:00 PM', '6:00:00 AM', '2:02:00 AM',
       '3:01:00 PM', '2:09:00 AM', '3:12:00 PM', '2:11:00 PM',
       '10:00:00 PM', '1:15:00 PM'], dtype=object)

In [ ]:
df['dinner'].unique()

array(['9:20:00 PM', '10:30:00 PM', '10:00:00 PM', '12:00:00 AM',
       '11:30:00 PM', '5:00:00 AM', '11:00:00 PM', '1:00:00 AM',
       '2:00:00 AM', '3:00:00 AM', '4:00:00 AM', '6:00:00 AM',
       '7:00:00 AM', '8:00:00 AM', '9:00:00 AM', '10:00:00 AM',
       '11:00:00 AM', '12:00:00 PM', '1:00:00 PM', '2:00:00 PM',
       '3:00:00 PM', '5:00:00 PM', '6:00:00 PM', '7:00:00 PM',
       '8:00:00 PM', '9:00:00 PM', '4:00:00 PM'], dtype=object)

In [ ]:
df['sleep'].unique()

array(['4:20:00 AM', '4:00:00 AM', '1:00:00 AM', '3:00:00 AM',
       '3:30:00 AM', '5:30:00 AM', '2:00:00 AM', '2:15:00 AM',
       '4:30:00 AM', '5:00:00 AM', '1:50:00 AM', '1:30:00 AM',
       '12:00:00 PM', '2:00:00 PM', '2:30:00 AM', '6:00:00 AM',
       '1:20:00 AM', '12:00:00 AM', '11:00:00 PM', '12:05:00 AM',
       '11:50:00 PM', '11:30:00 PM', '12:30:00 AM', '3:03:00 AM',
       '11:00:00 AM', '12:20:00 AM', '10:30:00 AM', '3:00:00 PM',
       '7:00:00 AM', '8:00:00 AM', '6:23:00 AM', '3:45:00 AM',
       '4:00:00 PM', '10:00:00 AM', '11:15:00 AM', '4:45:00 AM',
       '1:00:00 PM', '4:12:00 AM', '12:01:00 AM', '12:45:00 AM',
       '12:15:00 AM', '2:30:00 PM', '11:30:00 AM', '11:55:00 AM',
       '9:00:00 AM', '4:02:00 AM', '1:15:00 AM', '7:45:00 AM',
       '10:25:00 PM', '1:40:00 AM', '10:30:00 PM', '9:30:00 AM',
       '12:30:00 PM', '10:59:00 PM', '4:50:00 AM', '11:20:00 AM',
       '8:00:00 PM', '2:02:00 AM', '1:45:00 AM', '3:30:00 PM',
       '10:00:00 PM', '3:58:00 AM

In [ ]:
def convert24(str1):
    if str1[-2:] == "AM" and str1[:2] == "12":
        return "00" + str1[2:-3]
    elif str1[-2:] == "AM":
        return str1[:-3]
    elif str1[-2:] == "PM" and str1[1] == ":":
        return str(int(str1[0]) + 12) + str1[1:7]
    elif str1[-2:] == "PM" and str1[:2] == "12":
        return "00" + str1[2:-3]
    else:
        return str(int(str1[:2]) + 12) + str1[2:8]
    

In [ ]:
df['wakeup'] = df['wakeup'].map(lambda x: convert24(x))
df['breakfast'] = df['breakfast'].map(lambda x: convert24(x))
df['launch'] = df['launch'].map(lambda x: convert24(x))
df['dinner'] = df['dinner'].map(lambda x: convert24(x))
df['sleep'] = df['sleep'].map(lambda x: convert24(x))

In [ ]:
df['wakeup'].unique()

array(['11:20:00', '00:00:00', '8:30:00', '14:00:00', '11:00:00',
       '10:00:00', '9:30:00', '9:00:00', '9:40:00', '8:00:00', '6:00:00',
       '5:00:00', '7:00:00', '16:00:00', '9:20:00', '00:30:00', '7:50:00',
       '13:00:00', '15:00:00', '00:15:00', '00:10:00', '6:10:00',
       '7:30:00', '11:12:00', '5:30:00', '11:30:00', '10:30:00',
       '6:30:00', '00:12:00', '18:00:00', '13:30:00', '11:15:00',
       '4:00:00', '3:00:00', '9:15:00', '1:30:00', '00:05:00', '9:21:00',
       '4:30:00', '1:00:00', '11:38:00', '21:00:00', '11:50:00',
       '8:45:00', '4:50:00', '9:45:00', '8:50:00', '5:20:00', '8:20:00',
       '00:08:00', '6:45:00', '5:15:00', '4:35:00', '7:45:00', '10:20:00',
       '00:01:00', '7:38:00', '20:45:00', '4:20:00', '00:09:00',
       '9:09:00', '00:37:00', '13:40:00', '11:17:00', '5:45:00',
       '10:45:00', '10:10:00', '11:10:00', '11:11:00', '17:00:00',
       '7:20:00', '7:15:00', '00:06:00', '13:02:00'], dtype=object)

In [ ]:
def add0(str1):
  if int(str1[0]) == 2 and str1[1] != ":":
    return str1
  elif int(str1[0])==1 and str1[1] == ":":
     return "0"+ str1
  elif int(str1[0])>1 and str1[1] == ":":
     return "0"+ str1
  elif int(str1[0])<1 and str1[1] == ":":
     return "0"+ str1
  else:
     return str1

In [ ]:
def convert_float(str1):
  if int(str1[3:5]) >=30:
    return int(str1[:2])+1
  else:
     return int(str1[:2])

In [ ]:
#add0('23:00:00')
#df['wakeup'][3]
df['wakeup'] = df['wakeup'].map(lambda x: add0(x))
df['breakfast'] = df['breakfast'].map(lambda x: add0(x))
df['launch'] = df['launch'].map(lambda x: add0(x))
df['dinner'] = df['dinner'].map(lambda x: add0(x))
df['sleep'] = df['sleep'].map(lambda x: add0(x))

In [ ]:
df['breakfast'].unique()

array(['01:10:00', '00:15:00', '10:00:00', '15:00:00', '11:30:00',
       '16:00:00', '11:00:00', '13:00:00', '10:30:00', '11:10:00',
       '14:00:00', '00:00:00', '09:15:00', '08:30:00', '09:00:00',
       '11:11:00', '07:00:00', '11:20:00', '08:03:00', '09:30:00',
       '13:30:00', '00:30:00', '00:11:00', '11:15:00', '14:50:00',
       '13:01:00', '06:00:00', '10:15:00', '08:00:00', '14:30:00',
       '13:12:00', '09:20:00', '22:00:00', '06:30:00', '09:50:00',
       '09:45:00', '22:30:00', '15:07:00', '08:20:00', '01:00:00',
       '10:20:00', '11:25:00', '07:30:00', '10:50:00', '09:40:00',
       '10:45:00', '08:50:00', '07:45:00', '11:45:00', '00:20:00',
       '02:00:00', '09:10:00', '13:03:00', '23:00:00', '14:15:00',
       '06:45:00', '23:11:00', '14:45:00', '13:07:00', '10:52:00',
       '08:10:00', '23:30:00', '04:45:00', '14:05:00', '17:30:00',
       '00:08:00'], dtype=object)

In [ ]:
import time
import datetime
from datetime import timedelta
#from time import strftime
#from time import gmtime

#str(datetime.timedelta(seconds=60))
def sleep_h(s,w):
      if(w.hour <s.hour):
        new = w +timedelta(days = 1)
        return new-s
      else:
        return w-s

In [ ]:
i=0
li=[]   

while(i<len(df.index)):
    w= datetime.datetime.strptime(df['wakeup'][i],"%H:%M:%S")
    s= datetime.datetime.strptime(df['sleep'][i],"%H:%M:%S")
    #temp= sleep_h(s,w)
    #li.append([2,'d'])
    li.append(str(sleep_h(s,w)))
    #df["sleep_hours"][i]= sleep_h(s,w)
    i=i+1
df['sleep_hours']=li

In [ ]:
df['sleep_hours'] = df['sleep_hours'].map(lambda x: add0(x))

In [ ]:
df['sleep_hours'].unique()

array(['07:00:00', '20:00:00', '07:30:00', '11:00:00', '04:30:00',
       '06:30:00', '08:00:00', '06:00:00', '05:00:00', '07:45:00',
       '06:10:00', '08:30:00', '07:10:00', '19:00:00', '03:00:00',
       '09:00:00', '04:00:00', '10:00:00', '19:30:00', '07:40:00',
       '06:50:00', '21:00:00', '12:00:00', '22:00:00', '20:15:00',
       '09:30:00', '00:05:00', '06:20:00', '05:40:00', '05:30:00',
       '07:42:00', '20:57:00', '08:40:00', '15:00:00', '17:12:00',
       '04:52:00', '00:00:00', '16:00:00', '06:15:00', '18:00:00',
       '06:40:00', '05:21:00', '20:30:00', '17:15:00', '06:08:00',
       '06:18:00', '03:45:00', '09:20:00', '09:59:00', '21:45:00',
       '21:30:00', '07:15:00', '04:05:00', '04:15:00', '07:20:00',
       '05:20:00', '23:30:00', '00:08:00', '18:50:00', '21:05:00',
       '08:45:00', '18:30:00', '10:30:00', '05:28:00', '03:15:00',
       '09:10:00', '03:35:00', '08:20:00', '19:31:00', '06:38:00',
       '13:00:00', '03:20:00', '07:35:00', '07:50:00', '09:39:

In [ ]:
df['wakeup'] = df['wakeup'].map(lambda x: convert_float(x))
df['breakfast'] = df['breakfast'].map(lambda x: convert_float(x))
df['launch'] = df['launch'].map(lambda x: convert_float(x))
df['dinner'] = df['dinner'].map(lambda x: convert_float(x))
df['sleep'] = df['sleep'].map(lambda x: convert_float(x))
df['sleep_hours'] = df['sleep_hours'].map(lambda x: convert_float(x))

In [ ]:
df['wakeup'].unique()

array([11,  0,  9, 14, 10,  8,  6,  5,  7, 16,  1, 13, 15, 12, 18,  4,  3,
        2, 21, 17])

In [ ]:
df['breakfast'].unique()

array([ 1,  0, 10, 15, 12, 16, 11, 13, 14,  9,  7,  8,  6, 22, 23,  2, 24,
        5, 18])

In [ ]:
df['launch'].unique()

array([16, 17, 15, 19,  3, 14, 20,  2,  0, 18, 13,  4,  1,  5,  6, 22])

In [ ]:
df['dinner'].unique()

array([21, 23, 22,  0, 24,  5,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 13,
       14, 15, 17, 18, 19, 20, 16])

In [ ]:
df['sleep'].unique()

array([ 4,  1,  3,  6,  2,  5,  0, 14, 23, 24, 11, 15,  7,  8, 16, 10, 13,
       12,  9, 22, 20])

In [ ]:
df['sleep']

0      4
1      4
2      1
3      3
4      4
      ..
749    6
750    5
751    1
752    2
753    1
Name: sleep, Length: 754, dtype: int64

In [ ]:
df['wakeup']

0      11
1       0
2       9
3      14
4      11
       ..
749     9
750     0
751     7
752    11
753     8
Name: wakeup, Length: 754, dtype: int64

In [ ]:
df.head()

Unnamed: 0    mood  age  gender          subject semester sibilings  \
0           0  Tensed   24  Female      engineering        9         3   
1           1  Tensed   23    Male      engineering       11         3   
2           2     Sad   19  Female  bio and medical        3         0   
3           3    Lost   23  Female      engineering       13         1   
4           4    Lost   22    Male      engineering       11         1   

   living  employment  personality  ...  meditation  video_games  study_hours  \
0       0           1            0  ...  Not at all   Not at all            2   
1       0           0            1  ...   Sometimes    Sometimes            4   
2       0           0            1  ...  Not at all   Not at all            3   
3       0           0            2  ...  Not at all   Very Often            1   
4       0           0            1  ...  Not at all   Very Often            2   

   phone_hours  medication  movies_per_week  music hours  depression  \
0       6 to 8          No                0            0          18   
1       0 to 2          No                5            0           1   
2       6 to 8          No                0            0          21   
3       0 to 2          No                5            0          23   
4       6 to 8          No                1            4          19   

   category  sleep_hours  
0  Moderate            7  
1      None           20  
2    Severe            8  
3    Severe           11  
4  Moderate            8  

[5 rows x 36 columns]

In [ ]:
import pandas as pd;
print("Starting cleaning process for columns[social_events,pray,sports,exercise,meditation,video_games,study,hours]")
#Reading csv file
data = pd.read_csv('depression.csv')

#Handling Null values

#cleaning strings and converting to lowercase
data["social_events"] = data["social_events"].str.strip()
data["social_events"] = data["social_events"].str.lower()
data["video_games"] = data["video_games"].str.strip()
data["video_games"] = data["video_games"].str.lower()
data["pray"] = data["pray"].str.strip()
data["pray"] = data["pray"].str.lower()
data["sports"] = data["sports"].str.strip()
data["sports"] = data["sports"].str.lower()
data["exercise"] = data["exercise"].str.strip()
data["exercise"] = data["exercise"].str.lower()
data["meditation"] = data["meditation"].str.strip()
data["meditation"] = data["meditation"].str.lower()

#Mapping Ordinal data to numeric values
social_events_video_games_mapper = {"not at all":0, "sometimes":1, "often":2, "very often":3}
data["social_events"] = data["social_events"].replace(social_events_video_games_mapper)
data["video_games"] = data["video_games"].replace(social_events_video_games_mapper)
pray_sports_exercise_meditation_mapper = {"not at all":0, "sometimes":1, "regularly":2}
data["pray"] = data["pray"].replace(pray_sports_exercise_meditation_mapper)
data["sports"] = data["sports"].replace(pray_sports_exercise_meditation_mapper)
data["exercise"] = data["exercise"].replace(pray_sports_exercise_meditation_mapper)
data["meditation"] = data["meditation"].replace(pray_sports_exercise_meditation_mapper)


print("Ending cleaning process for columns[social_events,pray,sports,exercise,meditation,video_games,study,hours]")

Starting cleaning process for columns[social_events,pray,sports,exercise,meditation,video_games,study,hours]
Ending cleaning process for columns[social_events,pray,sports,exercise,meditation,video_games,study,hours]


In [ ]:
data.head()

mood  age  gender      subject  semester  sibilings       living  \
0  Tensed   24  Female  Engineering         9          3  With family   
1  Tensed   23    Male  Engineering        11          3  With family   
2     Sad   19  Female     Pharmacy         3          0  With family   
3    Lost   23  Female  Engineering        13          1  With family   
4    Lost   22    Male  Engineering        11          1  With family   

  employment personality       relationship  ... exercise meditation  \
0  Part time   Extrovert  In a relationship  ...        0          0   
1       None    Ambivert             Single  ...        2          1   
2       None    Ambivert             Single  ...        1          0   
3       None   Introvert  In a relationship  ...        0          0   
4       None    Ambivert             Single  ...        1          0   

  video_games study_hours phone_hours medication movies_per_week music hours  \
0           0           2      6 to 8         No               0           0   
1           1           4      0 to 2         No               5           0   
2           0           3      6 to 8         No               0           0   
3           3           1      0 to 2         No               5           0   
4           3           2      6 to 8         No               1           4   

  depression  category  
0         18  Moderate  
1          1      None  
2         21    Severe  
3         23    Severe  
4         19  Moderate  

[5 rows x 34 columns]

In [ ]:
# Data cleaning for the last 6 colomns:
# deleting two rows, which include null values in "medication":
df = df.dropna() 
# striping white spaces and converting upper cases in lower cases:
for col in ["phone_hours", "medication", "movies_per_week", "category"]:
    df[col] = df[col].str.strip().str.lower()
# getting the index of data in the colomn "movies_per_week", whose format are not proper and then deleting these datasets:
df.index[(df['movies_per_week']=="5-apr") | 
           (df['movies_per_week']== "4-feb") | 
           (df['movies_per_week']=="don't know")].tolist()
df = df.drop([21,23,25])
# changing the value including two numbers into an average: 
df = df.replace({"movies_per_week":{"1 or 2":"1.5"}})
# changing all values from string to integer:
df['movies_per_week'].apply(lambda x:int(float(x)))


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


0      0
1      5
2      0
3      5
4      1
      ..
749    0
750    0
751    0
752    3
753    0
Name: movies_per_week, Length: 749, dtype: int64